# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./main_win.h
SOURCES += ./main.cpp \
    ./main_win.cpp
FORMS += ./main_win.ui
RESOURCES += main_win.qrc
